### ISSUE TITLE
dsw-server purging database without prompting

### ISSUE THREAD

**Issue by talavis** [ds-wizard/ds-wizard#157]
We are working on doing a local deployment of dsw. Initially we used a checkout of the official dsw-server, but as we wanted to make some minor changes we decided to make a local fork.

When switching from the official version to our fork (which contained a total of one line change, only related to exporting) the server happily purged our database, deleting the entire knowledge model that was under development. It even happily told us it had done so by making a note in db.migrations.

I think deleting data in the database without any kind of prompting should be avoided, and would greatly appreciate if you can make sure no such things happen again.

**Comment by janslifka** [comment]
Dear Linus,

We are sorry about the situation. The cause for all this is that the metamodel of the knowledge model was still quite experimental and we didn't have time and resource to create proper migrations for that. So there is no way how to use the older knowledge models in the newer version. We migrated our core knowledge model manually as well.

That is not ideal, so we included versioning of the knowledge model metamodel [1] in version 1.4 of the Wizard (which should be out on 10th of March). All the following versions will have a mechanism to migrate all the existing knowledge models in the Wizard instance when updating [2]. Even then, we recommend to back up the database regularly as described in the documentation [3].

However, migration of knowledge model from versions before 1.4 is not possible in an automatic way.

We created an issue in our JIRA [4] to update the documentation asap to explain precisely how to update and that this can happen.

We have a registration form for local instance administrators [5] so that we can better communicate new releases and other information regarding the deployment. We invite you to register.

Thank you very much for your cooperation.


[1] https://ds-wizard.atlassian.net/browse/DSW-227
[2] https://ds-wizard.atlassian.net/browse/DSW-250
[3] https://docs.ds-wizard.org/installation#database-backup
[4] https://ds-wizard.atlassian.net/browse/DSW-253
[5] https://goo.gl/forms/9U4qoX25t1i6dcCo1

**Comment by talavis** [comment]
Thanks for the information. Is the elixir knowledge model also going to be updated? I tried adding the one linked in the documentation to 1.4, but got an error.

**Comment by MarekSuchanek** [comment]
Dear @talavis, we now merged the updated https://github.com/ds-wizard/km-elixir-root (current version compatible with `v1.4` is now in master).

**Comment by talavis** [comment]
I'm afraid it still won't work. The system only gives me the error message "Importing package failed.".

The knowledge model is from the linked repository (master branch), cloned a few minutes ago.

Both server and client are at version 1.4.0:

Client
--
Version | v1.4.0~7c44b1f
Built at | 2019/03/11 20:17:40Z

Server
--
Version | v1.4.0~a9da705
Built at | 2019/03/11 20:32:35Z

**Comment by MarekSuchanek** [comment]
I've just tried it on our pre-production environment and it works without any problems using exactly the same versions as u wrote.

Are you sure that you are using this one: https://raw.githubusercontent.com/ds-wizard/km-elixir-root/master/elixir-root.km? Also, the message should is different when there is error while parsing the file... Does some error message appear in the server's log for this action?

**Comment by talavis** [comment]
There is no output at all from the server. Going to the page for knowledge models give me [1], but the actual upload gives nothing at all from the server. I use the exact same file you linked. Has anything changed in the configuration file since 1.3.0? That's the only unique file I have.

[1] ```[Rqst] [U:cfebaa0b-135e-4cd5-9029-07b251ae559b][T:d369581d-466a-433e-8970-2cbe6f0aabc3] 200 OK GET /packages/unique```

**Comment by talavis** [comment]
The problem has been identified. The knowledge model is now greater than 1MB, meaning nginx was preventing the upload of the file. Setting e.g.` client_max_body_size 10M;` solved the problem.

**Comment by vknaisl** [comment]
Great to hear!

If you want to get updates about DS Wizard, you can register to our newsletter here (https://ds-wizard.org).

If you are using a self-hosted instance, we invite you to register it with our registration form so we can better communicate new releases and other important information regarding the deployment with you (https://goo.gl/forms/9U4qoX25t1i6dcCo1).
